name: Test Environment
on:
  workflow_dispatch:            # デフォルトブランチで手動実行

#  deployment:                    # デプロイを作成したときに
#  deployment_status:             # サードパーティによってデプロイの状態が提供されたときに

  # デプロイが成功した時に実行する。
  deployment_status:

env:
  # 認証情報（kinjoinfo2020）
  GH_HOST: github.com                                                   # 個人：GH Hostname
  GH_TOKEN: ${{ secrets.KINJO_GH_TOKEN }}                               # 個人：GHアクセストークン
  SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFY_BOT_TOKEN }}                # 個人：SLACK APIアクセストークン
  SLACK_CHANNEL: "github-actions-notification"

jobs:   
  dump_contexts-on-production-environment:
    runs-on: self-hosted
    environment:
      name: production
    steps:
      - name: Show Environment
        run: |
          echo "Current environment is Development, Current branch is ${{ github.ref }} "
          echo "github.event_name = ${{ github.event_name }}"
          echo "github.event.action = ${{ github.event.action }}"
          echo "github.event.check_run.status = ${{ github.event.check_run.status }}"
          echo "github.event.deployment_status.environment = ${{ github.event.deployment_status.environment }}"
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo secret ${{ secrets.TEST_SECRET_INFO }}
          echo "$GITHUB_CONTEXT"

  slack-notify:
    needs: dump_contexts-on-production-environment
    runs-on: self-hosted
    steps:
        # 「成功」の場合
      - name: Execute Result - Success
        if: success()
        run: |
          cat <<EOF > ./payload-slack-content.json
          {
           "attachments": [
             {
               "blocks": [
                 {
                   "type": "section",
                   "text": {
                     "type": "mrkdwn",
                     "text": "Successful: <${{ github.event.repository.html_url }}/actions/runs/${{ github.run_id }}| ${{ github.workflow }} - ${{ github.run_number }}>"
                   }
                 },
                 {
                   "type": "section",
                   "text": {
                     "type": "mrkdwn",
                     "text": "OK！*"
                   }
                 }
               ]
             }
           ]
          }
          EOF

      - name: Execute Result - Slack Notify
        uses: slackapi/slack-github-action@v1.24.0
        with:
          channel-id: '${{ env.SLACK_CHANNEL }}'
          payload-file-path: "./payload-slack-content.json"